config/routes.rb
Rails.application.routes.draw do
  get "/college_students/search", to: "college_students#search"
  resources :college_students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college_student.rb
class CollegeStudent < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/college_students_controller.rb
class CollegeStudentsController < ApplicationController
  before_action :set_college_student, only: %i[ show edit update destroy ]
  # GET /college_students or /college_students.json
  def index
    @college_students = ListCollegeStudents.run!
    render json: @college_students
  end

  # GET /college_students/1 or /college_students/1.json
  def show
    @find_college_student = find_college_student!
    render json: @find_college_student
  end

  # GET /college_students/new
  def new
    @college_student = CreateCollegeStudent.new
    render json: @college_student
  end

  # GET /college_students/1/edit
  def edit
    render json: find_college_student!

  end

  # POST /college_students or /college_students.json
  def create
    @college_student = CollegeStudent.new(college_student_params)

    respond_to do |format|
      if @college_student.save
        format.html { redirect_to @college_student, notice: "College student was successfully created." }
        format.json { render :show, status: :created, location: @college_student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @college_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /college_students/1 or /college_students/1.json
  def update
    inputs = { college_student: find_college_student! }.reverse_merge(params[:college_student])
    outcome = UpdateCollegeStudent.run(inputs)

    if outcome.valid?
      render json: outcome.result
    else
      @college_student = outcome
      render(:edit)
    end
  end

  # DELETE /college_students/1 or /college_students/1.json
  def destroy
    DestroyCollegeStudent.run!(college_student: find_college_student!)
    render json: {}
  end

  def search
    render :json => SearchCollegeStudent.run(params).result
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college_student
      @college_student = CollegeStudent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def college_student_params
      params.require(:college_student).permit(:name, :email)
    end

    def find_college_student!
      outcome = FindCollegeStudent.run(params)

      if outcome.valid?
        outcome.result
      else
        fail ActiveRecord::RecordNotFound, outcome.errors.full_messages.to_sentence
      end
    end

    def render_json(hash)
      render :json => hash
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/college_students_helper.rb
module CollegeStudentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/college_students/_form.html.erb
<%= form_with(model: college_student) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/college_students/edit.html.erb
<h1>Editing College Student</h1>

<%= render 'form', college_student: @college_student %>

<%= link_to 'Show', @college_student %> |
<%= link_to 'Back', college_students_path %>

app/views/college_students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>College Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @college_students.each do |college_student| %>
      <tr>
        <td><%= college_student.name %></td>
        <td><%= college_student.email %></td>
        <td><%= link_to 'Show', college_student %></td>
        <td><%= link_to 'Edit', edit_college_student_path(college_student) %></td>
        <td><%= link_to 'Destroy', college_student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College Student', new_college_student_path %>

app/views/college_students/new.html.erb
<h1>New College Student</h1>

<%= render 'form', college_student: @college_student %>

<%= link_to 'Back', college_students_path %>

app/views/college_students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college_student.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @college_student.email %>
</p>

<%= link_to 'Edit', edit_college_student_path(@college_student) %> |
<%= link_to 'Back', college_students_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>

app/views/pages/home.html.erb
<h1>Welcome to home</h1>